/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductOption } from "./ProductOption";
import { ProductOptionCountArgs } from "./ProductOptionCountArgs";
import { ProductOptionFindManyArgs } from "./ProductOptionFindManyArgs";
import { ProductOptionFindUniqueArgs } from "./ProductOptionFindUniqueArgs";
import { DeleteProductOptionArgs } from "./DeleteProductOptionArgs";
import { ProductOptionService } from "../productOption.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductOption)
export class ProductOptionResolverBase {
  constructor(
    protected readonly service: ProductOptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductOption",
    action: "read",
    possession: "any",
  })
  async _productOptionsMeta(
    @graphql.Args() args: ProductOptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductOption])
  @nestAccessControl.UseRoles({
    resource: "ProductOption",
    action: "read",
    possession: "any",
  })
  async productOptions(
    @graphql.Args() args: ProductOptionFindManyArgs
  ): Promise<ProductOption[]> {
    return this.service.productOptions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductOption, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductOption",
    action: "read",
    possession: "own",
  })
  async productOption(
    @graphql.Args() args: ProductOptionFindUniqueArgs
  ): Promise<ProductOption | null> {
    const result = await this.service.productOption(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductOption)
  @nestAccessControl.UseRoles({
    resource: "ProductOption",
    action: "delete",
    possession: "any",
  })
  async deleteProductOption(
    @graphql.Args() args: DeleteProductOptionArgs
  ): Promise<ProductOption | null> {
    try {
      return await this.service.deleteProductOption(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
