/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OptionValue } from "./OptionValue";
import { OptionValueCountArgs } from "./OptionValueCountArgs";
import { OptionValueFindManyArgs } from "./OptionValueFindManyArgs";
import { OptionValueFindUniqueArgs } from "./OptionValueFindUniqueArgs";
import { DeleteOptionValueArgs } from "./DeleteOptionValueArgs";
import { OptionValueService } from "../optionValue.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OptionValue)
export class OptionValueResolverBase {
  constructor(
    protected readonly service: OptionValueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OptionValue",
    action: "read",
    possession: "any",
  })
  async _optionValuesMeta(
    @graphql.Args() args: OptionValueCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OptionValue])
  @nestAccessControl.UseRoles({
    resource: "OptionValue",
    action: "read",
    possession: "any",
  })
  async optionValues(
    @graphql.Args() args: OptionValueFindManyArgs
  ): Promise<OptionValue[]> {
    return this.service.optionValues(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OptionValue, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OptionValue",
    action: "read",
    possession: "own",
  })
  async optionValue(
    @graphql.Args() args: OptionValueFindUniqueArgs
  ): Promise<OptionValue | null> {
    const result = await this.service.optionValue(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OptionValue)
  @nestAccessControl.UseRoles({
    resource: "OptionValue",
    action: "delete",
    possession: "any",
  })
  async deleteOptionValue(
    @graphql.Args() args: DeleteOptionValueArgs
  ): Promise<OptionValue | null> {
    try {
      return await this.service.deleteOptionValue(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
